// Code generated by entc, DO NOT EDIT.

package ent

import (
	"smpp/ent/messages"
	"smpp/ent/price"
	"smpp/ent/provide"
	"smpp/ent/rate"
	"smpp/ent/rateprice"
	"smpp/ent/schema"
	"smpp/ent/user"
	"smpp/ent/usermonthmessage"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	messagesFields := schema.Messages{}.Fields()
	_ = messagesFields
	// messagesDescSequenceNumber is the schema descriptor for sequence_number field.
	messagesDescSequenceNumber := messagesFields[1].Descriptor()
	// messages.SequenceNumberValidator is a validator for the "sequence_number" field. It is called by the builders before save.
	messages.SequenceNumberValidator = messagesDescSequenceNumber.Validators[0].(func(int32) error)
	// messagesDescCreateAt is the schema descriptor for create_at field.
	messagesDescCreateAt := messagesFields[8].Descriptor()
	// messages.DefaultCreateAt holds the default value on creation for the create_at field.
	messages.DefaultCreateAt = messagesDescCreateAt.Default.(func() time.Time)
	// messagesDescUpdateAt is the schema descriptor for update_at field.
	messagesDescUpdateAt := messagesFields[9].Descriptor()
	// messages.DefaultUpdateAt holds the default value on creation for the update_at field.
	messages.DefaultUpdateAt = messagesDescUpdateAt.Default.(func() time.Time)
	// messagesDescID is the schema descriptor for id field.
	messagesDescID := messagesFields[0].Descriptor()
	// messages.DefaultID holds the default value on creation for the id field.
	messages.DefaultID = messagesDescID.Default.(func() uuid.UUID)
	priceFields := schema.Price{}.Fields()
	_ = priceFields
	// priceDescMin is the schema descriptor for min field.
	priceDescMin := priceFields[1].Descriptor()
	// price.MinValidator is a validator for the "min" field. It is called by the builders before save.
	price.MinValidator = priceDescMin.Validators[0].(func(int32) error)
	// priceDescMax is the schema descriptor for max field.
	priceDescMax := priceFields[2].Descriptor()
	// price.MaxValidator is a validator for the "max" field. It is called by the builders before save.
	price.MaxValidator = priceDescMax.Validators[0].(func(int32) error)
	// priceDescCreateAt is the schema descriptor for create_at field.
	priceDescCreateAt := priceFields[4].Descriptor()
	// price.DefaultCreateAt holds the default value on creation for the create_at field.
	price.DefaultCreateAt = priceDescCreateAt.Default.(func() time.Time)
	// priceDescUpdateAt is the schema descriptor for update_at field.
	priceDescUpdateAt := priceFields[5].Descriptor()
	// price.DefaultUpdateAt holds the default value on creation for the update_at field.
	price.DefaultUpdateAt = priceDescUpdateAt.Default.(func() time.Time)
	// priceDescID is the schema descriptor for id field.
	priceDescID := priceFields[0].Descriptor()
	// price.DefaultID holds the default value on creation for the id field.
	price.DefaultID = priceDescID.Default.(func() uuid.UUID)
	provideFields := schema.Provide{}.Fields()
	_ = provideFields
	// provideDescCreateAt is the schema descriptor for create_at field.
	provideDescCreateAt := provideFields[3].Descriptor()
	// provide.DefaultCreateAt holds the default value on creation for the create_at field.
	provide.DefaultCreateAt = provideDescCreateAt.Default.(func() time.Time)
	// provideDescUpdateAt is the schema descriptor for update_at field.
	provideDescUpdateAt := provideFields[4].Descriptor()
	// provide.DefaultUpdateAt holds the default value on creation for the update_at field.
	provide.DefaultUpdateAt = provideDescUpdateAt.Default.(func() time.Time)
	// provideDescID is the schema descriptor for id field.
	provideDescID := provideFields[0].Descriptor()
	// provide.DefaultID holds the default value on creation for the id field.
	provide.DefaultID = provideDescID.Default.(func() uuid.UUID)
	rateFields := schema.Rate{}.Fields()
	_ = rateFields
	// rateDescCreateAt is the schema descriptor for create_at field.
	rateDescCreateAt := rateFields[2].Descriptor()
	// rate.DefaultCreateAt holds the default value on creation for the create_at field.
	rate.DefaultCreateAt = rateDescCreateAt.Default.(func() time.Time)
	// rateDescUpdateAt is the schema descriptor for update_at field.
	rateDescUpdateAt := rateFields[3].Descriptor()
	// rate.DefaultUpdateAt holds the default value on creation for the update_at field.
	rate.DefaultUpdateAt = rateDescUpdateAt.Default.(func() time.Time)
	// rateDescID is the schema descriptor for id field.
	rateDescID := rateFields[0].Descriptor()
	// rate.DefaultID holds the default value on creation for the id field.
	rate.DefaultID = rateDescID.Default.(func() uuid.UUID)
	ratepriceFields := schema.RatePrice{}.Fields()
	_ = ratepriceFields
	// ratepriceDescCreateAt is the schema descriptor for create_at field.
	ratepriceDescCreateAt := ratepriceFields[1].Descriptor()
	// rateprice.DefaultCreateAt holds the default value on creation for the create_at field.
	rateprice.DefaultCreateAt = ratepriceDescCreateAt.Default.(func() time.Time)
	// ratepriceDescUpdateAt is the schema descriptor for update_at field.
	ratepriceDescUpdateAt := ratepriceFields[2].Descriptor()
	// rateprice.DefaultUpdateAt holds the default value on creation for the update_at field.
	rateprice.DefaultUpdateAt = ratepriceDescUpdateAt.Default.(func() time.Time)
	// ratepriceDescID is the schema descriptor for id field.
	ratepriceDescID := ratepriceFields[0].Descriptor()
	// rateprice.DefaultID holds the default value on creation for the id field.
	rateprice.DefaultID = ratepriceDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescBalance is the schema descriptor for balance field.
	userDescBalance := userFields[1].Descriptor()
	// user.DefaultBalance holds the default value on creation for the balance field.
	user.DefaultBalance = userDescBalance.Default.(int16)
	// userDescCreateAt is the schema descriptor for create_at field.
	userDescCreateAt := userFields[2].Descriptor()
	// user.DefaultCreateAt holds the default value on creation for the create_at field.
	user.DefaultCreateAt = userDescCreateAt.Default.(func() time.Time)
	// userDescUpdateAt is the schema descriptor for update_at field.
	userDescUpdateAt := userFields[3].Descriptor()
	// user.DefaultUpdateAt holds the default value on creation for the update_at field.
	user.DefaultUpdateAt = userDescUpdateAt.Default.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
	usermonthmessageFields := schema.UserMonthMessage{}.Fields()
	_ = usermonthmessageFields
	// usermonthmessageDescMonth is the schema descriptor for month field.
	usermonthmessageDescMonth := usermonthmessageFields[1].Descriptor()
	// usermonthmessage.DefaultMonth holds the default value on creation for the month field.
	usermonthmessage.DefaultMonth = usermonthmessageDescMonth.Default.(func() time.Time)
	// usermonthmessageDescCreateAt is the schema descriptor for create_at field.
	usermonthmessageDescCreateAt := usermonthmessageFields[2].Descriptor()
	// usermonthmessage.DefaultCreateAt holds the default value on creation for the create_at field.
	usermonthmessage.DefaultCreateAt = usermonthmessageDescCreateAt.Default.(func() time.Time)
	// usermonthmessageDescUpdateAt is the schema descriptor for update_at field.
	usermonthmessageDescUpdateAt := usermonthmessageFields[3].Descriptor()
	// usermonthmessage.DefaultUpdateAt holds the default value on creation for the update_at field.
	usermonthmessage.DefaultUpdateAt = usermonthmessageDescUpdateAt.Default.(func() time.Time)
	// usermonthmessageDescID is the schema descriptor for id field.
	usermonthmessageDescID := usermonthmessageFields[0].Descriptor()
	// usermonthmessage.DefaultID holds the default value on creation for the id field.
	usermonthmessage.DefaultID = usermonthmessageDescID.Default.(func() uuid.UUID)
}
