// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Messages is the predicate function for messages builders.
type Messages func(*sql.Selector)

// Price is the predicate function for price builders.
type Price func(*sql.Selector)

// Provide is the predicate function for provide builders.
type Provide func(*sql.Selector)

// Rate is the predicate function for rate builders.
type Rate func(*sql.Selector)

// RatePrice is the predicate function for rateprice builders.
type RatePrice func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserMonthMessage is the predicate function for usermonthmessage builders.
type UserMonthMessage func(*sql.Selector)
